"環境設定
:set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [ASCII=\%03.3b]\ [HEX=\%02.2B]\ [POS=%04l,%04v][%p%%]\ [LEN=%L]
:set laststatus=2
"色の設定
:set background=dark
":colorscheme monokai
"syntax onはカラースキームを使うのに必要
:syntax on
set t_Co=256
"インデントの設定
set autoindent
"tabstop
set tabstop=4
set expandtab
set shiftwidth=4
"行番号をつける
set number
"文字コードの指定
set fenc=utf-8
set enc=utf-8
